export const SEND_LOCATION = 'SEND_USER_LOCATION';
export const SCAN = 'SCAN_NEARBY_USER';
export const QUEST_LIST = 'GET_QUEST_BY_EVENT_AND_USER'
export const VERIFY_QUEST = 'VERIFY_USER_ANSWER_QUEST'
export const SELECT_QUEST = 'SELECT_USER_EVENT_ID_FOR_CAMERA_UPDATE'
