import EventMap from './EventMap'
import GameEvent from './GameEvent'
// import Help from './Help'
import Home from './Home'
import ListEvent from './ListEvent1'
import Login from './Login'
// import UserProfile from './UserProfile'
// import cadangan from './cadangan'
export { Loading1, Loading2 } from './LoadingScreens'
export { GameEvent, Home, Login, ListEvent, EventMap }
